### PR TITLE
Updates 2018-11

### PR DESCRIPTION
**Pull request by esclapes**
Security update for `merge` (dependency of `jest`) and some other minor updates.

### CODE REVIEW

**Comment by esclapes** [comment]
I didn't check the version, and just now I see it is on a non-LTS `node:9.5.0-alpine` I wonder if there was an especific reason for it. Maybe @hharnisc has some extra context here?

Current LTS is `10.13.0`, so we could update to that one.

This branch goes against `next`, so no rush to merge.

**Comment by philippemiguet** [comment]
@esclapes no sure to understand the reference to `node:9.5.0-alpine`? 😅

**Comment by esclapes** [comment]
Oh! I am sorry @philippemiguet. I can see how it is confusing. 

Only our `next` branch is on `node:9.5.0-alpine` because it is not up to date with `master` and there was a PR #10 where the Dockerfile was fixed to use LTS in `master`.

I did not realize of this divergence before, so I assumed it was clear that `buffer-login` [was using `node:9.5.0-alpine`](https://github.com/bufferapp/buffer-login/blob/next/Dockerfile#L1) :sweat_smile: 

In order to avoid merge conflicts, we could:

1. go ahead and merge this one to `next`
2. bring `next` up to date with `master` changes
3. create a new PR to update to the latest node:8 version

How does that sound to you?

**Comment by philippemiguet** [comment]
Ah yes, I see, I was looking at the code on master that's why I didn't see the 9.5.0 version! your plan sounds good!

**Pull request merged**
