### PR TITLE
Docker image fixes

### PR DESCRIPTION
**Pull request by djfarrelly**
### Purpose
To move to the [LTS version](https://github.com/nodejs/Release) of node and ensure we do not wrap the command with `npm start` in production.

### CODE REVIEW

**Comment by philippemiguet** [comment]
@djfarrelly **LGTM** to use the latest active LTS.

Should we update the version in buffer-account, core-authentication-service and session-service? They all use `FROM node:8.1.2-alpine` or `FROM node:8.1.2-slim` (for dev).

**Comment by philippemiguet** [comment]
@djfarrelly - shall we merge it? :)

**Comment by djfarrelly** [comment]
Hey @philippemiguet, yeah, let's merge this, sorry was tied up. Would you mind merging this? This repo has continuous delivery right?

**Comment by philippemiguet** [comment]
@djfarrelly yes it has! I will merge it tomorrow so I can monitor things. It's getting toward the end of my day now :)

**Pull request merged**
