### PR TITLE
Fix 50 security vulnerabilities

### PR DESCRIPTION
**Pull request by josem**
Fixed with:
``` 
npm audit fix
```

### CODE REVIEW

**Comment by esclapes** [comment]
Thanks a lot for sending this through @josem :taco: 

@philippemiguet we have fixed the vulnerabilities in `next` branch but not in `master`. Should we just go ahead and merge this one and deal with the conflicts in `next` or shall we just wait?

**Comment by josem** [comment]
Ah so sorry @esclapes! I didn't know you worked on the next branch instead. 

Feel free to close this PR then if that's easier. I saw the notification and I jumped on it right away without the right context so no worries at all if you prefer to merge the changes on next later.

Thanks so much for taking a look! 🤗

**Comment by esclapes** [comment]
Thanks again for sending this PR, Jose. Going to close for now as it would be tricky to merge this back into `next` which is planned to be released soon.

**Comment by josem** [comment]
Good, no worries! Thank you @esclapes! 🙂

**Pull request closed without merging**
